package net.pside.android.example.mostpowerfulorminandroid;

import net.pside.android.example.mostpowerfulorminandroid.DaoSession;
import de.greenrobot.dao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CHILD_TWO.
 */
public class ChildTwo {

    private Long id;
    private Long ChildThreeId;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient ChildTwoDao myDao;

    private ChildTwo childTwo;
    private Long childTwo__resolvedKey;


    public ChildTwo() {
    }

    public ChildTwo(Long id) {
        this.id = id;
    }

    public ChildTwo(Long id, Long ChildThreeId) {
        this.id = id;
        this.ChildThreeId = ChildThreeId;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getChildTwoDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getChildThreeId() {
        return ChildThreeId;
    }

    public void setChildThreeId(Long ChildThreeId) {
        this.ChildThreeId = ChildThreeId;
    }

    /** To-one relationship, resolved on first access. */
    public ChildTwo getChildTwo() {
        Long __key = this.ChildThreeId;
        if (childTwo__resolvedKey == null || !childTwo__resolvedKey.equals(__key)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            ChildTwoDao targetDao = daoSession.getChildTwoDao();
            ChildTwo childTwoNew = targetDao.load(__key);
            synchronized (this) {
                childTwo = childTwoNew;
            	childTwo__resolvedKey = __key;
            }
        }
        return childTwo;
    }

    public void setChildTwo(ChildTwo childTwo) {
        synchronized (this) {
            this.childTwo = childTwo;
            ChildThreeId = childTwo == null ? null : childTwo.getId();
            childTwo__resolvedKey = ChildThreeId;
        }
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

}
