package net.pside.android.example.mostpowerfulorminandroid;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CHILD_FIVE.
 */
public class ChildFive {

    private Long id;
    private String ormName;

    public ChildFive() {
    }

    public ChildFive(Long id) {
        this.id = id;
    }

    public ChildFive(Long id, String ormName) {
        this.id = id;
        this.ormName = ormName;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getOrmName() {
        return ormName;
    }

    public void setOrmName(String ormName) {
        this.ormName = ormName;
    }

}
