package net.pside.android.example.mostpowerfulorminandroid;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import net.pside.android.example.mostpowerfulorminandroid.Simple;
import net.pside.android.example.mostpowerfulorminandroid.ChildOne;
import net.pside.android.example.mostpowerfulorminandroid.ChildTwo;
import net.pside.android.example.mostpowerfulorminandroid.ChildThree;
import net.pside.android.example.mostpowerfulorminandroid.ChildFour;
import net.pside.android.example.mostpowerfulorminandroid.ChildFive;

import net.pside.android.example.mostpowerfulorminandroid.SimpleDao;
import net.pside.android.example.mostpowerfulorminandroid.ChildOneDao;
import net.pside.android.example.mostpowerfulorminandroid.ChildTwoDao;
import net.pside.android.example.mostpowerfulorminandroid.ChildThreeDao;
import net.pside.android.example.mostpowerfulorminandroid.ChildFourDao;
import net.pside.android.example.mostpowerfulorminandroid.ChildFiveDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig simpleDaoConfig;
    private final DaoConfig childOneDaoConfig;
    private final DaoConfig childTwoDaoConfig;
    private final DaoConfig childThreeDaoConfig;
    private final DaoConfig childFourDaoConfig;
    private final DaoConfig childFiveDaoConfig;

    private final SimpleDao simpleDao;
    private final ChildOneDao childOneDao;
    private final ChildTwoDao childTwoDao;
    private final ChildThreeDao childThreeDao;
    private final ChildFourDao childFourDao;
    private final ChildFiveDao childFiveDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        simpleDaoConfig = daoConfigMap.get(SimpleDao.class).clone();
        simpleDaoConfig.initIdentityScope(type);

        childOneDaoConfig = daoConfigMap.get(ChildOneDao.class).clone();
        childOneDaoConfig.initIdentityScope(type);

        childTwoDaoConfig = daoConfigMap.get(ChildTwoDao.class).clone();
        childTwoDaoConfig.initIdentityScope(type);

        childThreeDaoConfig = daoConfigMap.get(ChildThreeDao.class).clone();
        childThreeDaoConfig.initIdentityScope(type);

        childFourDaoConfig = daoConfigMap.get(ChildFourDao.class).clone();
        childFourDaoConfig.initIdentityScope(type);

        childFiveDaoConfig = daoConfigMap.get(ChildFiveDao.class).clone();
        childFiveDaoConfig.initIdentityScope(type);

        simpleDao = new SimpleDao(simpleDaoConfig, this);
        childOneDao = new ChildOneDao(childOneDaoConfig, this);
        childTwoDao = new ChildTwoDao(childTwoDaoConfig, this);
        childThreeDao = new ChildThreeDao(childThreeDaoConfig, this);
        childFourDao = new ChildFourDao(childFourDaoConfig, this);
        childFiveDao = new ChildFiveDao(childFiveDaoConfig, this);

        registerDao(Simple.class, simpleDao);
        registerDao(ChildOne.class, childOneDao);
        registerDao(ChildTwo.class, childTwoDao);
        registerDao(ChildThree.class, childThreeDao);
        registerDao(ChildFour.class, childFourDao);
        registerDao(ChildFive.class, childFiveDao);
    }
    
    public void clear() {
        simpleDaoConfig.getIdentityScope().clear();
        childOneDaoConfig.getIdentityScope().clear();
        childTwoDaoConfig.getIdentityScope().clear();
        childThreeDaoConfig.getIdentityScope().clear();
        childFourDaoConfig.getIdentityScope().clear();
        childFiveDaoConfig.getIdentityScope().clear();
    }

    public SimpleDao getSimpleDao() {
        return simpleDao;
    }

    public ChildOneDao getChildOneDao() {
        return childOneDao;
    }

    public ChildTwoDao getChildTwoDao() {
        return childTwoDao;
    }

    public ChildThreeDao getChildThreeDao() {
        return childThreeDao;
    }

    public ChildFourDao getChildFourDao() {
        return childFourDao;
    }

    public ChildFiveDao getChildFiveDao() {
        return childFiveDao;
    }

}
