package net.pside.android.example.mostpowerfulorminandroid;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import net.pside.android.example.mostpowerfulorminandroid.Simple;

import net.pside.android.example.mostpowerfulorminandroid.SimpleDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig simpleDaoConfig;

    private final SimpleDao simpleDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        simpleDaoConfig = daoConfigMap.get(SimpleDao.class).clone();
        simpleDaoConfig.initIdentityScope(type);

        simpleDao = new SimpleDao(simpleDaoConfig, this);

        registerDao(Simple.class, simpleDao);
    }
    
    public void clear() {
        simpleDaoConfig.clearIdentityScope();
    }

    public SimpleDao getSimpleDao() {
        return simpleDao;
    }

}
